spring:
  application:
    name: JWT-Authentication-and-Authorisation-with-SpringBoot-Security-6
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_learn_db
    username: postgres
    password: postgres12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      #tell spring what to do at the start-up of the application or et the update
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    #this will help spring performing and writing better queries to match postgres SQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

